use trip;

CREATE TABLE `CAMPING_PLACE` (
	`CONTENT_ID`	BIGINT	NOT NULL primary key 	COMMENT '컨텐츠ID',
	`DO_NAME`	VARCHAR(255)	NOT NULL	COMMENT '시도',
	`SIGUNGU_NAME`	VARCHAR(255)	NOT NULL	COMMENT '시군구',
	`SINK_CNT`	INT	NOT NULL	COMMENT '개수대개수',
	`BRAZIER`	TEXT	NOT NULL	COMMENT '화로대',
	`CAN_CARAVAN`	VARCHAR(255)	NOT NULL	COMMENT '개인카라반동반여부',
	`TOILET_CNT`	INT	NULL	COMMENT '화장실개수',
	`SHAWERROOM_CNT`	INT	NULL	COMMENT '샤워실개수',
	`FEATURE`	TEXT	NOT NULL	COMMENT '특징',
	`INDUTY`	VARCHAR(255)	NOT NULL	COMMENT '업종',
	`ZIPCODE`	INT	NOT NULL	COMMENT '우편번호',
	`ADDRESS`	VARCHAR(255)	NOT NULL	COMMENT '주소',
	`MAP_X`	VARCHAR(255)	NOT NULL	COMMENT '경도',
	`MAP_Y`	VARCHAR(255)	NOT NULL	COMMENT '위도',
	`TEL`	VARCHAR(255)	NULL	COMMENT '전화번호',
	`HOMEPAGE`	VARCHAR(255)	NULL	COMMENT '홈페이지',
	`RESERVE_URL`	TEXT	NULL	COMMENT '예약페이지',
	`RESERVE_TYPE`	VARCHAR(255)	NULL	COMMENT '예약구분',
	`MANAGE_NUM`	INT	NULL	COMMENT '상주관리인원',
	`OPER_SEASON`	VARCHAR(255)	NOT NULL	COMMENT '운영기간',
	`OPER_DATE`	VARCHAR(255)	NOT NULL	COMMENT '운영일',
	`CAN_TRAILER`	VARCHAR(255)	NOT NULL	COMMENT '개인트레일러동반여부',
	`INTRO`	VARCHAR(255)	NULL	COMMENT '소개',
	`AREA`	INT	NULL	COMMENT '전체면적',
	`MANAGE_STATUS`	VARCHAR(255)	NULL	COMMENT '운영상태',
	`EQUIP_LEND`	VARCHAR(255)	NULL	COMMENT '캠핑장비대여',
	`ANIMAL`	VARCHAR(255)	NULL	COMMENT '애완동물출입',
	`FIRST_IMAGE_URL`	TEXT	NULL	COMMENT '대표이미지',
	`CAMPSITE_NAME`	VARCHAR(255)	NOT NULL	COMMENT '야영장명',
	`LINE_INTRO`	VARCHAR(255)	NULL	COMMENT '한줄소개',
	`FACLT_DIV_NAME`	VARCHAR(255)	NOT NULL	COMMENT '사업주체',
	`LOCATION_TYPE`	VARCHAR(255)	NULL	COMMENT '입지구분',
	`SITE_TYPE_GRASS`	INT	NULL	COMMENT '잔디',
	`SITE_TYPE_CRUSHED`	INT	NULL	COMMENT '파쇄석',
	`SITE_TYPE_TECH`	INT	NULL	COMMENT '테크',
	`SITE_TYPE_PEBBLE`	INT	NULL	COMMENT '자갈',
	`SITE_TYPE_SOIL`	INT	NULL	COMMENT '맨흙',
	`GENERAL_SITE_CNT`	INT	NULL	COMMENT '주요시설 일반야영장',
	`AUTO_SITE_CNT`	INT	NULL	COMMENT '주요시설 자동차 야영장',
	`GLAMP_SITE_CNT`	INT	NULL	COMMENT '주요시설 글램핑',
	`CARAVAN_SITE_CNT`	INT	NULL	COMMENT '주요시설 카라반',
	`USER_CARAVAN_SITE_CNT`	INT	NULL	COMMENT '주요시설 개인 카라반',
	`ETC_FACILITIES`	TEXT	NULL	COMMENT '주요시설 기타',
	`ETC_CARAVAN_FACILITIES`	TEXT	NULL	COMMENT '카라반 시설',
	`ETC_GLAMPING_FACILITIES`	TEXT	NULL	COMMENT '글램핑 시설',
	'EXPERIENCE' TEXT NULL COMMENT '체험 프로그램'
);

CREATE TABLE `SUB_FACILITIES` (
	`SUB_FACILITIES_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '부대시설 ID',
	`NAME`	VARCHAR(255)	NOT NULL	COMMENT '부대시설 이름'
);

CREATE TABLE `EXPERIENCE` (
	`EXPERIENCE_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '체험 프로그램 ID',
	`NAME`	VARCHAR(255)	NOT NULL	COMMENT '체험프로그램 이름'
);


CREATE TABLE `THEME` (
	`THEME_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '테마ID',
	`NAME`	VARCHAR(255)	NOT NULL	COMMENT '테마 이름'
);

CREATE TABLE `OPERATION_TYPE` (
	`OPERATION_TYPE_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '운영형태 ID',
	`NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `MEMBER` (
	`MEMBER_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '유저 ID',
	`LOGIN_ID`	VARCHAR(255)	NOT NULL	COMMENT '유저 로그인 아이디',
	`NAME`	VARCHAR(20)	NOT NULL	COMMENT '유저이름'
);

CREATE TABLE `MAIN_FACILITIES` (
	`MAIN_FACILITIES_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '메인시설 ID',
	`NAME`	VARCHAR(255)	NOT NULL	COMMENT '메인시설 이름'
);

CREATE TABLE `LOCATION_TYPE` (
	`LOCATION_TYPE_ID`	BIGINT	NOT NULL primary key auto_increment	COMMENT '입지구분ID',
	`NAME`	VARCHAR(255)	NULL
);


CREATE TABLE `CAPING_PLACE_THEME` (
	`CAMPING_PLACE_THEME_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`THEME_ID`	BIGINT	NOT NULL	COMMENT '테마ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (THEME_ID) references THEME(THEME_ID)
);

CREATE TABLE `CAPING_PLACE_MAIN_FACILITIES` (
	`CAPING_PLACE_MAIN_FACILITIES_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`MAIN_FACILITIES_ID`	BIGINT	NOT NULL	COMMENT '메인시설 ID',
    foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (MAIN_FACILITIES_ID) references MAIN_FACILITIES(MAIN_FACILITIES_ID)
);

CREATE TABLE `CAMPING_PLACE_OPERATION_TYPE` (
	`CAMPING_PLACE_OPERATION_TYPE_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`OPERATION_TYPE_ID`	BIGINT	NOT NULL	COMMENT '운영형태 ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (OPERATION_TYPE_ID) references OPERATION_TYPE(OPERATION_TYPE_ID)
);

CREATE TABLE `CAMPING_PLACE_LOCATION_TYPE` (
	`CAMPING_PLACE_LOCATION_TYPE_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`LOCATION_TYPE_ID`	BIGINT	NOT NULL	COMMENT '입지구분ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (LOCATION_TYPE_ID) references LOCATION_TYPE(LOCATION_TYPE_ID)
);

CREATE TABLE `CAMPING_PLACE_SUB_FACILITIES` (
	`CAMPING_PLACE_SUB_FACILITIES_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`SUB_FACILITIES_ID`	BIGINT	NOT NULL	COMMENT '부대시설 ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (SUB_FACILITIES_ID) references SUB_FACILITIES(SUB_FACILITIES_ID)
);

CREATE TABLE `CAMPING_PLACE_EXPERIENCE` (
	`COMPAING_PLACE_EXPERIENCE_ID`	BIGINT	NOT NULL primary key auto_increment,
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	`EXPERIENCE_ID`	BIGINT	NOT NULL	COMMENT '체험 프로그램 ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (EXPERIENCE_ID) references EXPERIENCE(EXPERIENCE_ID)
);

CREATE TABLE `CAMPING_USER_LIKE` (
	`CAMPING_UESR_LIKE_ID`	BIGINT	NOT NULL primary key auto_increment,
	`USER_ID`	BIGINT	NOT NULL	COMMENT '유저 ID',
	`CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
	foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID),
	foreign key (USER_ID) references member(MEMBER_ID)
);

CREATE TABLE CAMPING_PLACE_IMG(
    `CAMPING_PLACE_IMG_ID` BIGINT not null primary key auto_increment,
    `CONTENT_ID`	BIGINT	NOT NULL	COMMENT '컨텐츠ID',
    `IMG_URL` TEXT NOT NULL ,
    foreign key (CONTENT_ID) references CAMPING_PLACE(CONTENT_ID)
)